/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamIdRouteImport } from './routes/$examId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamIdIndexRouteImport } from './routes/$examId/index'
import { Route as ExamIdStreamIdRouteImport } from './routes/$examId/$streamId'
import { Route as ExamIdStreamIdIndexRouteImport } from './routes/$examId/$streamId/index'
import { Route as ExamIdStreamIdSubjectSlugTopicSlugRouteImport } from './routes/$examId/$streamId.$subjectSlug.$topicSlug'

const ExamIdRoute = ExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIdIndexRoute = ExamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamIdRoute,
} as any)
const ExamIdStreamIdRoute = ExamIdStreamIdRouteImport.update({
  id: '/$streamId',
  path: '/$streamId',
  getParentRoute: () => ExamIdRoute,
} as any)
const ExamIdStreamIdIndexRoute = ExamIdStreamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamIdStreamIdRoute,
} as any)
const ExamIdStreamIdSubjectSlugTopicSlugRoute =
  ExamIdStreamIdSubjectSlugTopicSlugRouteImport.update({
    id: '/$subjectSlug/$topicSlug',
    path: '/$subjectSlug/$topicSlug',
    getParentRoute: () => ExamIdStreamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$examId': typeof ExamIdRouteWithChildren
  '/$examId/$streamId': typeof ExamIdStreamIdRouteWithChildren
  '/$examId/': typeof ExamIdIndexRoute
  '/$examId/$streamId/': typeof ExamIdStreamIdIndexRoute
  '/$examId/$streamId/$subjectSlug/$topicSlug': typeof ExamIdStreamIdSubjectSlugTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$examId': typeof ExamIdIndexRoute
  '/$examId/$streamId': typeof ExamIdStreamIdIndexRoute
  '/$examId/$streamId/$subjectSlug/$topicSlug': typeof ExamIdStreamIdSubjectSlugTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$examId': typeof ExamIdRouteWithChildren
  '/$examId/$streamId': typeof ExamIdStreamIdRouteWithChildren
  '/$examId/': typeof ExamIdIndexRoute
  '/$examId/$streamId/': typeof ExamIdStreamIdIndexRoute
  '/$examId/$streamId/$subjectSlug/$topicSlug': typeof ExamIdStreamIdSubjectSlugTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$examId'
    | '/$examId/$streamId'
    | '/$examId/'
    | '/$examId/$streamId/'
    | '/$examId/$streamId/$subjectSlug/$topicSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$examId'
    | '/$examId/$streamId'
    | '/$examId/$streamId/$subjectSlug/$topicSlug'
  id:
    | '__root__'
    | '/'
    | '/$examId'
    | '/$examId/$streamId'
    | '/$examId/'
    | '/$examId/$streamId/'
    | '/$examId/$streamId/$subjectSlug/$topicSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamIdRoute: typeof ExamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$examId': {
      id: '/$examId'
      path: '/$examId'
      fullPath: '/$examId'
      preLoaderRoute: typeof ExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$examId/': {
      id: '/$examId/'
      path: '/'
      fullPath: '/$examId/'
      preLoaderRoute: typeof ExamIdIndexRouteImport
      parentRoute: typeof ExamIdRoute
    }
    '/$examId/$streamId': {
      id: '/$examId/$streamId'
      path: '/$streamId'
      fullPath: '/$examId/$streamId'
      preLoaderRoute: typeof ExamIdStreamIdRouteImport
      parentRoute: typeof ExamIdRoute
    }
    '/$examId/$streamId/': {
      id: '/$examId/$streamId/'
      path: '/'
      fullPath: '/$examId/$streamId/'
      preLoaderRoute: typeof ExamIdStreamIdIndexRouteImport
      parentRoute: typeof ExamIdStreamIdRoute
    }
    '/$examId/$streamId/$subjectSlug/$topicSlug': {
      id: '/$examId/$streamId/$subjectSlug/$topicSlug'
      path: '/$subjectSlug/$topicSlug'
      fullPath: '/$examId/$streamId/$subjectSlug/$topicSlug'
      preLoaderRoute: typeof ExamIdStreamIdSubjectSlugTopicSlugRouteImport
      parentRoute: typeof ExamIdStreamIdRoute
    }
  }
}

interface ExamIdStreamIdRouteChildren {
  ExamIdStreamIdIndexRoute: typeof ExamIdStreamIdIndexRoute
  ExamIdStreamIdSubjectSlugTopicSlugRoute: typeof ExamIdStreamIdSubjectSlugTopicSlugRoute
}

const ExamIdStreamIdRouteChildren: ExamIdStreamIdRouteChildren = {
  ExamIdStreamIdIndexRoute: ExamIdStreamIdIndexRoute,
  ExamIdStreamIdSubjectSlugTopicSlugRoute:
    ExamIdStreamIdSubjectSlugTopicSlugRoute,
}

const ExamIdStreamIdRouteWithChildren = ExamIdStreamIdRoute._addFileChildren(
  ExamIdStreamIdRouteChildren,
)

interface ExamIdRouteChildren {
  ExamIdStreamIdRoute: typeof ExamIdStreamIdRouteWithChildren
  ExamIdIndexRoute: typeof ExamIdIndexRoute
}

const ExamIdRouteChildren: ExamIdRouteChildren = {
  ExamIdStreamIdRoute: ExamIdStreamIdRouteWithChildren,
  ExamIdIndexRoute: ExamIdIndexRoute,
}

const ExamIdRouteWithChildren =
  ExamIdRoute._addFileChildren(ExamIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamIdRoute: ExamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
